version: '3.8'
services:
  pucapp_shopping:
    build: .
    image: pucapp_shopping
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/shopping_db
    networks:
      - pucapp_infra_pucapp_network
networks:
  pucapp_infra_pucapp_network:
    external: true